Repository nuxt/test-utils, pull requests merged in 2024-05, with the labels that each got.

#843 feat(deps): upgrade `execa` to v9
  package.json
  pnpm-lock.yaml
  src/core/server.ts
  src/core/types.ts
Labels: enhancement, size:S

#851 ci: run test suite on windows
  .github/workflows/ci.yml
  package.json
  patches/nuxt@3.11.2.patch
  pnpm-lock.yaml
Labels: enhancement, size:S

#849 fix(runtime-utils): use `appId` fallback after `tryUseNuxtApp`
  src/config.ts
  src/runtime-utils/mount.ts
  src/runtime-utils/render.ts
Labels: bug, size:XS

#852 feat(runtime-utils): expose setup context from `renderSuspended` result
  examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
  src/runtime-utils/render.ts
Labels: vitest-environment, size:L, lgtm
