Repository nuxt/test-utils, pull requests merged in 2024-07, with the labels that each got.

#877 fix(runtime-utils): `setProps` can replace array prop
  examples/app-vitest-full/components/ExportDefaultComponent.vue
  examples/app-vitest-full/components/ExportDefaultReturnsRenderComponent.vue
  examples/app-vitest-full/components/ExportDefaultWithRenderComponent.vue
  examples/app-vitest-full/components/ExportDefineComponent.vue
  examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
  src/runtime-utils/mount.ts
Labels: bug, size:M, lgtm

#903 feat(e2e): allow overwriting env variables in `setup`
  src/core/setup/index.ts
  src/core/types.ts
Labels: enhancement, size:XS, lgtm

#803 feat: allow to run e2e tests against existing server
  src/core/context.ts
  src/core/nuxt.ts
  src/core/server.ts
  src/core/types.ts
Labels: enhancement, size:M

#812 feat(e2e): allow updating env in context before `setup` runs
  examples/app-playwright/app.vue
  examples/app-playwright/nuxt.config.ts
  examples/app-playwright/tests/basic.test.ts
  src/core/server.ts
Labels: size:S, lgtm
