Repository nuxt/test-utils, pull requests merged in 2024-08, with the labels that each got.

#906 chore: provide intellisense hints on setup properties
  src/core/types.ts
Labels: size:M, lgtm

#911 fix: avoid error message with tsc and nuxt test-utils
  src/module.ts
Labels: bug, size:XS, lgtm

#919 chore: Add 'MIT' license to vitest-environment-nuxt package.json
  stubs/vitest-environment-nuxt/package.json
Labels: vitest-environment, size:XS, lgtm
